"""
SLR(1) shift-reduce parser for SPL
uses an SLR table generated by slr_table.py when fed grammar.py

utilises the node class from the xmlwriter, since this is what we need to 
create our DS out of. if changes happen there inshallah idk
"""

import sys
from pathlib import Path
from typing import List

from xmlwriter.node import Node  # we need to create our tree out of these nodes
from .grammar import START
from .slr_table import build_slr_table, GrammarConflictError, PRODS


class SyntaxError_(Exception):
    def __init__(self, message: str, hint: str = ""):
        full = message + (f"\n  Hint: {hint}" if hint else "")
        super().__init__(full)


# basically just an adapter from what I assumed to what was built in lexer.py
# Lexer kind -> grammar terminal, for kinds that are not literal text
# Anything not in this map falls back to using the token's own text as
# the terminal symbol (covers KEYWORD/SYMBOL-style lexers where kind is
# just a category label and the literal string is what the grammar cares
# about, e.g. lexer.py: kind='KEYWORD', lexeme='if').
_KIND_TO_TERMINAL = {
    "NAME": "USER-DEFINED-NAME",   # lexer.py's kind name for USER-DEFINED-NAME
    "NUM": "NUM",
    "STRING": "STRING",
}


def _token_text(tok) -> str:
    if hasattr(tok, "lexeme"):
        return tok.lexeme
    return tok.text  #fallback that should never actually happen


def _token_line(tok) -> int:
    return getattr(tok, "line", -1)


def _token_col(tok) -> int:
    return getattr(tok, "col", -1)


class Parser:
    def __init__(self, tokens: List):
        self.tokens = tokens
        try:
            self.table = build_slr_table()
        except GrammarConflictError as e:
            # This would mean a bug in grammar.py, not in the user's input
            raise RuntimeError(f"Internal grammar error: {e}") from e

    @staticmethod
    def _terminal_of(tok) -> str:
        """Map a Token to the grammar terminal symbol it satisfies."""
        if tok.kind in _KIND_TO_TERMINAL:
            return _KIND_TO_TERMINAL[tok.kind]
        return _token_text(tok)

    def _expected_symbols(self, state: int) -> List[str]:
        return sorted(
            sym for (s, sym) in self.table.action.keys() if s == state
        )

    def parse(self) -> Node:
        # Append the SLR end-of-input marker, distinct from SPLs own
        # $ token (which is part of the grammar itself)
        # stilll not really sure how to handle the end token but this should work
        class _EndToken:
            kind = "#END#"
            lexeme = "#"
            line = -1
            col = -1

        stream = list(self.tokens) + [_EndToken()]
        pos = 0

        state_stack = [0]
        node_stack: List[Node] = []

        # main loop, just keep accepting tokens until either something screws up or
        # we reach the end of the token stream
        while True:
            state = state_stack[-1]
            tok = stream[pos]
            term = "#" if tok.kind == "#END#" else self._terminal_of(tok)

            action = self.table.action.get((state, term))

            # reached the end. figure out of good end or bad end
            if action is None:
                expected = self._expected_symbols(state)
                at_end = tok.kind == "#END#"
                where = (
                    "end of input" if at_end
                    else f"line {_token_line(tok)}, col {_token_col(tok)}"
                )
                got = "end of input" if at_end else f"'{_token_text(tok)}'"
                raise SyntaxError_(
                    f"Syntax error at {where}: unexpected {got}.",
                    f"Expected one of: {', '.join(expected)}"
                )

            if action[0] == "shift":
                node_stack.append(self._make_leaf(tok))
                state_stack.append(action[1])
                pos += 1

            elif action[0] == "reduce":
                prod_idx = action[1]
                lhs, rhs = PRODS[prod_idx]
                n = len(rhs)
                children = node_stack[len(node_stack) - n:] if n else []
                if n:
                    del node_stack[len(node_stack) - n:]
                    del state_stack[len(state_stack) - n:]
                # SPL_PROG never appears on the RHS of any production
                # (only the augment rule uses it), so reducing it means were always at the root of the tree
                node_type = "root" if lhs == START else "inner"
                new_node = self._make_inner(lhs, node_type, children)
                node_stack.append(new_node)
                top_state = state_stack[-1]
                goto_state = self.table.goto_table.get((top_state, lhs))
                if goto_state is None:
                    raise RuntimeError(
                        f"Internal parser error: no GOTO for state "
                        f"{top_state} on '{lhs}'."
                    )
                state_stack.append(goto_state)

            elif action[0] == "accept":
                # node_stack has exactly one node, the SPL_PROG root. we successfully worked backwards to here
                assert len(node_stack) == 1
                return node_stack[0]

    def _make_leaf(self, tok) -> Node:
        return Node(contents=_token_text(tok), node_type="leaf")

    def _make_inner(self, name: str, node_type: str, children: List[Node]) -> Node:
        node = Node(contents=name, node_type=node_type)
        for c in children:
            node.add_child(c)
        return node


def parse_tokens(tokens: List) -> Node:
    """Convenience wrapper: tokens -> root Node (SPL_PROG), or raises
    SyntaxError_ on malformed input."""
    return Parser(tokens).parse()